version: "2.4"

volumes:
  config:
  cache:

services:

  ssh:
    image: alpine
    command: /bin/sh -c "apk add openssh-client bash && /bin/bash /usr/local/bin/tunnel"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./tunnel.sh:/usr/local/bin/tunnel
      - ./keys/:/keys

  jellyfin:
    image: jellyfin/jellyfin
    runtime: nvidia
    ports:
      - 80:8096
    restart: unless-stopped
    env_file: .env
    environment:
      - JELLYFIN_PublishedServerUrl=http://${REMOTE_HOST:-localhost}
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - config:/config
      - cache:/cache
      - type: bind
        source: /media/fletch/Music
        target: /media/Music
      - type: bind
        source: /media/fletch/Music2
        target: /media/Music2
      - type: bind
        source: /media/fletch/Music3
        target: /media/Music3
      - type: bind
        source: /media/fletch/Music4
        target: /media/Music4
      - type: bind
        source: /media/fletch/MusicNew
        target: /media/MusicNew
      - type: bind
        source: /media/fletch/TV
        target: /media/TV
      - type: bind
        source: /media/fletch/Movies
        target: /media/Movies
      - type: bind
        source: /media/fletch/Books
        target: /media/Books
      - type: bind
        source: ./
        target: /app

